name: IaC Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  accuknox-cicd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main  
   
      - name: Run IaC Scan
        uses: ./
        with:      
          token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzEwNDAwNzM3LCJqdGkiOiI4ZDRiNmQ3Y2IzODM0M2Y0YmRiMzc1MjIzNzM2NmI3MyIsImlzcyI6ImNzcG0uZGV2LmFjY3Vrbm94LmNvbSJ9.ZeHoaDVdF2vX70FWE7cxKfepst63hX1JeDOkvkPZicxXmYMv5CHi4wWZ1zbrF-5F0_2rV6Nb3dADC-qo4l99dbK4XmbzjSg4wgUKE6ObwoFUo17LuNpIv23_jpOOIkx2DvrSVZCDvAwLqQUCpBzZjoLr3nNWu_OUnHmiLN8D8ttz92EOhLOE7vjehXL5tMSoZYtHf5OzuvMjWxhAo1EJ94GxO0B5n-mg4qZXdm5_6AHwUdW9smZY_XQ38FlQhuEo21BkgP2DTwrpn9ZECYswJaK8atHBo7TaDwCbdaq8nLceLtZQYpXv61SAF_NdBQ9AOxyRuWQVQeFvyoM4wcfqUg"
          # repository_name: "udit-uniyal/vulnerable-to-test"
          endpoint: "cspm.dev.accuknox.com"
          tenant_id: "1034"
