name: 'Accuknox IaC Scan'
description: 'Run Scan against infrastructure as code.'
inputs:
  token:
    description: 'The token for authenticating with the CSPM panel.'
    required: true
  tenant_id:
    description: 'The ID of the tenant associated with the CSPM panel.'
    required: true
  endpoint:
    description: 'The URL of the CSPM panel to push the scan results to.'
    required: true
    default: 'cspm.demo.accuknox.com'
  github_pat:
    description: 'Environment variable name for a Github personal access token for scanning external modules sourced from private repositories'
    required: false
  quiet:
    description: 'Environment variable name for a Github personal access token for scanning external modules sourced from private repositories'
    required: false
  directory:
    description: 'dir to scan'
    required: false
runs:
  using: 'composite'
  steps: 
      - name: Install Checkov
        run: pip install checkov > /dev/null
        shell: bash

      - name: Run IaC Scan
        run: |
          checkov {{ env.directory }} {{ inputs.quiet }} -o json > scan_results.json || true
        env:
          directory: "-d {{ inputs.directory }}"
        shell: bash 
        
      - name: Print IaC Scan Results
        run: cat scan_results.json
        shell: bash
        
      - name: Push report to CSPM panel
        run: |
          curl --location --request POST 'https://${{ inputs.endpoint }}/api/v1/artifact/?tenant_id=${{ inputs.tenant_id }}&data_type=IAC&save_to_s3=false' --header 'Tenant-Id: ${{ inputs.tenant_id }}' --header 'Authorization: Bearer ${{ inputs.token }}' --form 'file=@"./scan_results.json"'
        shell: bash
        
      - name: Remove temporary files
        run: |
          rm scan_results.json
        shell: bash

        
branding:
  icon: 'shield'
  color: 'purple'
